language: cpp
matrix:
  include:
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      before_install:
        - sudo apt-get install -y libopenal-dev
      before_script:
        - export CXX=g++-4.9
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      before_install:
        - sudo apt-get install -y libopenal-dev
      before_script:
        - export CXX=g++-5
    - compiler: clang
      os: osx
      osx_image: xcode7.2
      before_script:
        - export CXX=clang++
script:
  - cd samples && make