dist: trusty  
language: cpp
matrix:
  include:
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      before_install:
        - sudo apt-get install -y libopenal-dev
        - sudo apt-get install -y libasound2-dev
        - sudo apt-get install -y libxi-dev
        - sudo apt-get install -y libxcursor-dev
      before_script:
        - export CXX=g++-4.9
      script:
        - make -j2 -f samples/Makefile
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
        sonarcloud:
          organization: "elnormous-github"
          token:
            secure: "L4nEr4rHuk4Le7jFQyAFNVsI+m7rsInUHPwhQMVPfUQq1gYdy2NzijLVY2Y/DMvmuxn0NgI/AN2b/FcY+qD8vWa4tz07BrRL5PAu+uISSQayVdKE7ELS8ENVrwGPIbpuk5RQpBVCpJOn1SbOmjSPcqHwfedLVt6cqAk/mCXbGBQd0As8YhGTDFwFtxXMD1TNwqpXCSLnUQKsatbtAb1BUH6erBCzTvFquevx70S/c0zv40gB1slla5MQwXrs14IQqJT05TQqJVgls5t4p+C4aZg0nZ3XRIGfpNyUkedod3cW7YW8UJX4brzFjqHyA2EiND3um9ov9aj7ZwRtmlavJs6w/cMS+eFBjAQmW3TZythe7oPYFZAc3c86KDQo0z9h836e7Sav/sGz/BvCpEa9ofTJJoROV8TobP2bWWFqoz0hPj3t8PDnuaoEuQeFdAh5ZjIuQ8OcGJrRMKoowqSWLiFs1XSUSvTU6f+Vhm7BWHuZc+FvmnpXxkJfG+0o4hzOSsQuspKhSrcy5bMJAi5rkxnkMheNKQBS8HZ6tpKwlJYVPX8gJQvfCwX6Z+Srfv22mPuWv/JpPG/NKPrxOHDa7aAQx6irGj+oDjucNmu0L9bkMhPuK3eNwtd6m0eoGAxDdq017gvY7EdczF00TbDNpwUDF4cqEeb7Fg5AQ5F48Tc="
      before_install:
        - sudo apt-get install -y libopenal-dev
        - sudo apt-get install -y libasound2-dev
        - sudo apt-get install -y libxi-dev
        - sudo apt-get install -y libxcursor-dev
      before_script:
        - export CXX=g++-5
      script:
        - build-wrapper-linux-x86-64 --out-dir bw-output make -j2 -f samples/Makefile
        - sonar-scanner -D sonar.projectKey=Ouzel -D sonar.projectName="Ouzel Linux"
    - compiler: clang
      os: osx
      osx_image: xcode7.3
      addons:
        sonarcloud:
          organization: "elnormous-github"
          token:
            secure: "L4nEr4rHuk4Le7jFQyAFNVsI+m7rsInUHPwhQMVPfUQq1gYdy2NzijLVY2Y/DMvmuxn0NgI/AN2b/FcY+qD8vWa4tz07BrRL5PAu+uISSQayVdKE7ELS8ENVrwGPIbpuk5RQpBVCpJOn1SbOmjSPcqHwfedLVt6cqAk/mCXbGBQd0As8YhGTDFwFtxXMD1TNwqpXCSLnUQKsatbtAb1BUH6erBCzTvFquevx70S/c0zv40gB1slla5MQwXrs14IQqJT05TQqJVgls5t4p+C4aZg0nZ3XRIGfpNyUkedod3cW7YW8UJX4brzFjqHyA2EiND3um9ov9aj7ZwRtmlavJs6w/cMS+eFBjAQmW3TZythe7oPYFZAc3c86KDQo0z9h836e7Sav/sGz/BvCpEa9ofTJJoROV8TobP2bWWFqoz0hPj3t8PDnuaoEuQeFdAh5ZjIuQ8OcGJrRMKoowqSWLiFs1XSUSvTU6f+Vhm7BWHuZc+FvmnpXxkJfG+0o4hzOSsQuspKhSrcy5bMJAi5rkxnkMheNKQBS8HZ6tpKwlJYVPX8gJQvfCwX6Z+Srfv22mPuWv/JpPG/NKPrxOHDa7aAQx6irGj+oDjucNmu0L9bkMhPuK3eNwtd6m0eoGAxDdq017gvY7EdczF00TbDNpwUDF4cqEeb7Fg5AQ5F48Tc="
      before_script:
        - export CXX=clang++
      script:
        - build-wrapper-macosx-x86 --out-dir bw-output make -j2 -f samples/Makefile
        - sonar-scanner -D sonar.projectKey=OuzelMacOS -D sonar.projectName="Ouzel macOS"
    - compiler: clang
      os: osx
      osx_image: xcode7.3
      addons:
        sonarcloud:
          organization: "elnormous-github"
          token:
            secure: "L4nEr4rHuk4Le7jFQyAFNVsI+m7rsInUHPwhQMVPfUQq1gYdy2NzijLVY2Y/DMvmuxn0NgI/AN2b/FcY+qD8vWa4tz07BrRL5PAu+uISSQayVdKE7ELS8ENVrwGPIbpuk5RQpBVCpJOn1SbOmjSPcqHwfedLVt6cqAk/mCXbGBQd0As8YhGTDFwFtxXMD1TNwqpXCSLnUQKsatbtAb1BUH6erBCzTvFquevx70S/c0zv40gB1slla5MQwXrs14IQqJT05TQqJVgls5t4p+C4aZg0nZ3XRIGfpNyUkedod3cW7YW8UJX4brzFjqHyA2EiND3um9ov9aj7ZwRtmlavJs6w/cMS+eFBjAQmW3TZythe7oPYFZAc3c86KDQo0z9h836e7Sav/sGz/BvCpEa9ofTJJoROV8TobP2bWWFqoz0hPj3t8PDnuaoEuQeFdAh5ZjIuQ8OcGJrRMKoowqSWLiFs1XSUSvTU6f+Vhm7BWHuZc+FvmnpXxkJfG+0o4hzOSsQuspKhSrcy5bMJAi5rkxnkMheNKQBS8HZ6tpKwlJYVPX8gJQvfCwX6Z+Srfv22mPuWv/JpPG/NKPrxOHDa7aAQx6irGj+oDjucNmu0L9bkMhPuK3eNwtd6m0eoGAxDdq017gvY7EdczF00TbDNpwUDF4cqEeb7Fg5AQ5F48Tc="
      before_script:
        - export CXX=clang++
      script:
        - build-wrapper-macosx-x86 --out-dir bw-output make platform=ios -j2 -f samples/Makefile
        - sonar-scanner -D sonar.projectKey=OuzelIOS -D sonar.projectName="Ouzel iOS"
    - compiler: clang
      os: osx
      osx_image: xcode7.3
      addons:
        sonarcloud:
          organization: "elnormous-github"
          token:
            secure: "jQOQ1SK/1VKTtafovC39X/mTGXdc5S5qlDWHTDY7GOEceX+MldobaJ/RdiVR32h3OyM3n7ZhRolTGI+rX1wNyWEsxPQSJ8mOmVAYppldk7ueG/SPDmNnTIzeiw80aY+OtbXugFZija7iB63LsItcN4AgCJRGqjSYHSlqu7u0u1v0oq/uH6qeja/H32rIl2tWr0RilNedQamaumH3KTojQYioJ8dkGnFkksjAs1K0F/k9QsojmqNOk2HSN2Chp9WY1RMArLJCRbK4ND1SyAlsLPBlBLgJ6+rYQ4NYCJIJYiwyao2nRTw9Tx1leFP3PBcNbwmEwa3guvtF2p5wMSG1Gnfs9JeENunQbKbtBLXHSVMaH0NP0TNYgJ/ONVGDiwid7K9R7/EcN0HxyaITWACskyRchyuDHl0RS3Jf0qfWcgEeMe8Ri6fMwEjXiTQrAcveJWVShsA59DXbKfwWz5wpST/i+GqJuv9KYmnLIGfU6kFnsRc+OsDLBqd5Eu4j8Hwu5nd1wjVdpHsHAi3X61evVK07idW+aK2Mx8Bp89wtjdsTMMun1d4rLCJzcIoWG8jBpTrh2EgWlQ2UQtWZdmA0vfHV9T+QCwDAwHItOJYtGk14HqE/QorhtFnX9B8hm6qTgC0MA2Vfvw0qswC6ifcuWqFV2RM5aetcwq8Qg8hGAZk="
      before_script:
        - export CXX=clang++
      script:
        - build-wrapper-macosx-x86 --out-dir bw-output make platform=tvos -j2 -f samples/Makefile
        - sonar-scanner -D sonar.projectKey=OuzelTVOS -D sonar.projectName="Ouzel tvOS"