#dist: trusty
#sudo: required
addons:
  sonarcloud:
    organization: "elnormous-github"
    token:
      secure: "Gbeh1ryGBFTaPSp+NKuc2him0a/8tdqDabDft0COCTC5EVn5d/gC5uQ3vSOZwYMoU9EEO4XUvVcrROGCrUVCOqtxI+rUhan/37eMNXo2gbwBIl8tBmDkXcqtp8WwX0ErBuyU0WJPWYpcXdokclPxiNiiXEzTQJ57p67CJupaPdByBuZ3TcnyaWjzr3H/LGrTXVELGlb7N42ugGUpCLcnk2s+ITVB1H/TEDyo5VEm2SvjHvzfKuirHS3xRh7cYwYl2Mnkc99mDUFPYUao9sWvqACArW9D3XxXoBwzwbHATAaBz9ghtIsJ8L1fhRYBjRVTRH/bRGpFRq1Mi21yjHacZSuztdaEAQS7Mij7Ti7KLVYphZ113Ni1yno8fOqjqnqmcXGfCMHKNg4b40q4XwtUa8c0WUcNbUHqHpr9w+M33sxDlmEItfut488nVj1nwemp8HIAtMCnTIYvNI3OZ8WHxmIYXPjXqI7c6pPY9LAw9CsOoHyI5NfRB9JhZsLV60UNrm1xOd1qoQb4ANTRHFZoUlLxO2HxT/EMj1RO0+lRiIRXOI04/wYavPa/OHUA+Zx9pE+FFZMVFB6nd71jW7vsZaumtQh3P59eERU37IUFEygw+ul982SVK/yUTlsxkr0sgPFYLSxXFSzfxWvvGIXuXKdl0dNNFaC+J405gAXZGpo="
language: cpp
matrix:
  include:
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      before_install:
        - sudo apt-get install -y libopenal-dev
        - sudo apt-get install -y libasound2-dev
        - sudo apt-get install -y libxi-dev
        - sudo apt-get install -y libxcursor-dev
      before_script:
        - export CXX=g++-4.9
      script:
        - cd samples
        - make -j2
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      before_install:
        - sudo apt-get install -y libopenal-dev
        - sudo apt-get install -y libasound2-dev
        - sudo apt-get install -y libxcursor-dev
      before_script:
        - export CXX=g++-5
      script:
        - cd samples
        - make -j2
    - compiler: clang
      os: osx
      osx_image: xcode7.3
      before_script:
        - export CXX=clang++
      script:
        - cd samples
        - make -j2
        - make clean
        - make platform=ios -j2
        - make clean
        - make platform=tvos -j2
#cache:
#  directories:
#    - '$HOME/.sonar/cache'
#script:
#  - sonar-scanner