trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - script: sudo apt-get install -y libopenal-dev
  - script: sudo apt-get install -y libasound2-dev
  - script: sudo apt-get install -y libxi-dev
  - script: sudo apt-get install -y libxcursor-dev
  - script: sudo apt-get install -y libxss-dev
  - script: |
      cd samples
      make -j2
    displayName: 'make'

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - script: MSBuild.exe samples/samples.vcxproj /property:Configuration=Release